name: Run Shell Script

on:
  push:
    branches: [master]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./.github/workdlows/deploy.sh

      - name: Run deploy script
        run: ./.github/workflows/deploy.sh
